{% set name = "wxPython" %}
{% set version = "3.0.2.0" %}
{% set sha256 = "d54129e5fbea4fb8091c87b2980760b72c22a386cb3b9dd2eebc928ef5e8df61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: wxPython-src-{{ version }}.tar.bz2  # [not win]
   url: http://sourceforge.net/projects/wxpython/files/wxPython/{{ version }}/wxPython-src-{{ version }}.tar.bz2  # [not win]
   sha256: {{ sha256 }}  # [not win]
   fn: {{ version }}.zip  # [win]
   # NOTE: this is a re-distribution of the wheels from: http://www.lfd.uci.edu/~gohlke/pythonlibs/
   url: https://github.com/NOAA-ORR-ERD/wxpython_wheels/archive/{{ version }}.zip  # [win]
   sha256: 3b40fad724172cd7186af95224ae5bf45262c405aac62f8441fe24f0a7a91429  # [win]

build:
  number: 0
  skip: True  # [osx or linux or py3k or win32]

requirements:
  build:
    - python >=2.7,<3
    - pip

  run:
    - python

test:
  imports:
    - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows
  license_family: LGPL
  license_file: docs/licence.txt  # [not win]
  summary: 'Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
  description: |
    With wxPython software developers can create truly native user interfaces
    for their Python applications, that run with little or no modifications
    on Windows, Macs and Linux or other unix-like systems.
  home: https://wxpython.org/
  doc_url: https://docs.wxpython.org/
  dev_url: https://github.com/wxWidgets/wxPython

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - Korijn
    - ocefpaf
