{% set name = "wxPython" %}
{% set version = "3.0.2.0" %}
{% set sha256 = "d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: wxPython-src-{{ version }}.tar.bz2 # [not win]
   url: http://sourceforge.net/projects/wxpython/files/wxPython/{{ version }}/wxPython-src-{{ version }}.tar.bz2 # [not win]
   sha256: {{ sha256 }}
   fn: {{ version }}.zip # [win]
   url: https://github.com/NOAA-ORR-ERD/wxpython_wheels/archive/{{ version }}.zip [win]
   sha256: {{ sha256 }} # [win]

build:
  number: 0

  script: $RECIPE_DIR/build_osx.sh # [osx]
  script: $RECIPE_DIR/build.sh # [linux]
  script: "%RECIPE_DIR%/bld.bat" # [win]
  skip: False  # [win]
  skip: True   # [linux]
  skip: True  # [osx] # until I get the build errors figured out

requirements:
  build:
    - python >=2.7,<3
    - setuptools
    - pip
    - toolchain # [not win]

  run:
    - python

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  license_family: LGPL
  # license_file: LICENSE.txt
  summary: 'Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
  description: |
    With wxPython software developers can create truly native user interfaces
    for their Python applications, that run with little or no modifications
    on Windows, Macs and Linux or other unix-like systems.
  home: https://wxpython.org/
  doc_url: https://docs.wxpython.org/
  dev_url: https://github.com/wxWidgets/wxPython

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
