package:
  name: wxpython
  version: "3.0.2.0"

source:
   fn: wxPython-src-3.0.2.0.tar.bz2 #[not win]
   url: http://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2 #[not win]
   git_url: https://github.com/NOAA-ORR-ERD/wxpython_wheels.git
#   - url: https://github.com/NOAA-ORR-ERD/wxpython_wheels/blob/master/wheels/wxPython_common-3.0.2.0-py2-none-any.whl #[win]
#     folder: wheels #[win]
#   - url: https://github.com/NOAA-ORR-ERD/wxpython_wheels/blob/master/wheels/wxPython-3.0.2.0-cp27-none-win_amd64.whl
#     folder: wheels #[win]
  # path:  ./wheels #[win]

build:
  number: 2

  script: $RECIPE_DIR/build_osx.sh # [osx]
  script: $RECIPE_DIR/build.sh # [linux]
  script: "%RECIPE_DIR%/bld.bat" # [win]
  skip: False  #[win]
  skip: True   #[linux]
  skip: False  #[osx] # until I get the build errors figured out

requirements:
  build:
    - python >=2.7,<3
    - setuptools
    - pip

  run:
    - python

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: 'Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
