{% set name = "hieroglyph" %}
{% set version = "1.0.0" %}
{% set sha256 = "8e137f0b1cd60c47b870011089790d3c8ddb74fcf409a75ddf2c7f2516ff337c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - sphinx
    - six

test:
  imports:
    - hieroglyph

about:
  home: http://docs.hieroglyph.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  # LICENSE file not included in sdist on PyPI -- PR submitted
  # license_file:

  summary: 'An extension for Sphinx which builds HTML presentations from ReStructured Text documents.'

  doc_url: http://docs.hieroglyph.io/en/latest/
  dev_url: https://github.com/nyergler/hieroglyph

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
